version: "3"

services:
  backend:
    image: docker.io/shernille37/backend:latest
    ports:
      - "3000:3000"
    volumes:
      - image:/app/images
      - database:/app/db

  frontend:
    image: docker.io/shernille37/frontend:latest
    ports:
      - "8080:80"

volumes:
  image:
  database:
